---
authors:
- admin
categories: [Investigación, Inteligencia Artificial, Seminario, INARBE, Escuela de Doctorado]
date: 2019-10-14T08:26:17+02:00
draft: false
featured: false
image:
  caption: ""
  focal_point: "Center"
projects: [ ]
subtitle:  
title: "Jornadas Doctorales INARBE: Seminario Inteligencia Artificial y Marketing"
tags: [Blogs, Docencia, Dropbox, Herramientas 2.0, Recursos Educativos, repositorios, Scribd, Slideshare]
---

Los pasados 10 y 11 de octubre, el grupo de investigación en marketing en la UPNA organizamos en el Instituto de Investigación INARBE las jornadas doctorales Inteligencia Artificial y Marketing.  El encuentro estaba pensado como forma de compartir experiencias desde distintos puntos de vista en la línea de investigación en Inteligencia Artificial  y como jornada formativa para los doctorandos en el instituto.

El jueves por la tarde tuvimos tres ponencias de empresa. [Patricia Durán, de Planeta Chatbot]( https://planetachatbot.com/@patriciadurana ) nos presentó experiencias variadas en la implantación de este nuevo canal de comunicación con consumidores, ciudadanos, proveedores y empleados. Después Omar Rois de [Xeerpa]( https://xeerpa.com/inicio/ ) nos dejó con la boca abierta con las posibilidades que tiene su herramienta para la segmentación y personalización de la comunicación con los clientes. Para cerrar, desde [Bikolabs]( https://www.biko2.com/bikolabs-creatividad-pirata/ ), Ujué Agudo y Karlos G. Liberal nos presentaron un marco muy interesante, la narrativa de la convivencia, desde el que entender la relación humano-tecnología, incluyendo una adaptación de la pirámide de Maslow con muchas aplicaciones. Cerramos la jornada con una mesa redonda en la que pudimos compartir visiones sobre el dilema personalización-privacidad.

El viernes tuvimos tres aproximaciones al problema desde puntos de vista muy distintos. [Edurne Barrenechea]( http://www.unavarra.es/pdi?uid=2578 ), investigadora en el área de Inteligencia Artificial en la UPNA nos presentó los mitos y las realidades en este ámbito. [María Jorqui]( http://www.unavarra.es/pdi?uid=810823 ) , investigadora en derecho civil también en la UPNA, nos presentó los desafíos y dilemas legales que se presentan para las empresas, los consumidores y los legisladores y, por último, [Helena Matute]( https://helenamatute.wordpress.com/ ), de la Universidad de Deusto  y directora del [Laboratorio de Psicología Experimental](https://labpsicoblog.wordpress.com/) , nos presentó como los sesgos en el razonamiento humano se aplican también a las decisiones de los algoritmos y los riesgos que presenta esta tecnología para la toma de decisiones de forma no condicionada. Estas tres visiones complementan perfectamente la línea de investigación en Inteligencia Artificial que estamos abordando en el grupo de marketing, así que la mesa redonda fue muy enriquecedora. Se quedaron pendientes muchos temas, ¡así que igual tenemos que repetir la experiencia!. 

¡Gracias a todos los ponentes por su esfuerzo desinteresado, así como a todos los asistentes por venir a acompañarnos y por las excelentes preguntas!

El programa completo de la jornada puede consultarse en  https://www.unavarra.es/research-institutes/tablon+de+anuncios?contentId=245011 

