# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Mónica Cortiñas"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"


# Default language to use (if you setup multilingual support)
defaultContentLanguage = "es"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-59823480-1"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "Mónica Cortiñas &copy; 2020"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false


# Enable comments by entering your Disqus shortname
disqusShortname = "monicacortinas-net-1"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = true

[languages]
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 10
    [[languages.es.menu.main]]
    name   = "Inicio"
    url = "#about"
     weight = 10
    [[languages.es.menu.main]]
  name = "Publicaciones"
  url = "#featured"
  weight = 20
    [[languages.es.menu.main]]
  name = "Proyectos"
  url = "#projects"
  weight = 30
    [[languages.es.menu.main]]
  name = "Clases"
  url = "courses/"
  weight = 40
    [[languages.es.menu.main]]
  name = "Conferencias"
  url = "talk/"
  weight = 50
  [[languages.es.menu.main]]
  name = "Blog"
  url = "#posts"
  weight = 60
  [[languages.es.menu.main]]
  name = "Contacto"
  url = "#contact"
  weight = 70
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 20
    [[languages.en.menu.main]]
      name   = "Home"
      url = "#about"
       weight = 10
    [[languages.en.menu.main]]
  name = "Publications"
  url = "#featured"
  weight = 20
  [[languages.en.menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 30
    [[languages.en.menu.main]]
  name = "Recent Talks"
  url = "talk/"
  weight = 40
    [[languages.en.menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 70
  
  
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

