---
authors:
- admin
categories: [AEMARK 2015, Investigación, Marketing, ]
date: 2015-05-23T08:26:17+02:00
draft: false
featured: false
image:
  caption: " "
  focal_point: "Center"
projects: []
subtitle: El congreso Aemark se celebra en Pamplona
title: "XXVII Congreso de Marketing Aemark 2015"
tags: [AEMARK 2015, Investigación, Marketing]
---

El área de marketing de la UPNA estamos organizando la [XXVII edición del Congreso de Marketing Aemark](http://www.aemarkcongresos.com/congreso2015/es/) que se celebrará en Pamplona los días 9, 10 y 11 de septiembre. Esta está siendo una experiencia completamente nueva y sumamente enriquecedora.

Queda una semana para el envío de comunicaciones.  Se aceptan propuestas de ponencias, trabajos en curso y propuestas de póster en Comportamiento del Consumidor y Consumo, Marketing Estratégico, Innovación y Decisiones de Producto y Marca, Comunicación y Ventas, TIC, e-marketing y mobile marketing, Distribución Comercial y Gestión Minorista, Marketing Multisectorial, Ética y Responsabilidad Corportiva y, por último, Docencia en Marketing.

Como veis, contenidos muy variados para un congreso que promete. Como aperitivo, el miércoles 9 tendremos un Doctoral Colloquium donde estudiantes de doctorado podrán debatir sus propuestas con investigadores con muchísima experiencia. El jueves y viernes, además de las sesiones generales de ponencias, tendremos una sesión especial *"Meet the editors"* con dos editores de revistas internacionales de alto impacto y una sesión especial *"Casos de Éxito"* donde intercambiaremos experiencias con directivos.

El viernes cerraremos con Cena de Clausura en la que, esperamos, la gastronomía navarra sepa estar a la altura.